// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyFileName():Promise<void>;

export function DelFile():Promise<void>;

export function OpenFile():Promise<void>;

export function RenameFile():Promise<void>;

export function SelectDir():Promise<string>;

export function TraversalFiles(arg1:string):Promise<void>;
