// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyFileName() {
  return window['go']['main']['App']['CopyFileName']();
}

export function DelFile() {
  return window['go']['main']['App']['DelFile']();
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function RenameFile() {
  return window['go']['main']['App']['RenameFile']();
}

export function SelectDir() {
  return window['go']['main']['App']['SelectDir']();
}

export function TraversalFiles(arg1) {
  return window['go']['main']['App']['TraversalFiles'](arg1);
}
